김자경 과제 제출
GDSC-SKHU/GDSC-Server-Assignment-03 pull request #5
Opened 2022-11-11 10:37 UTC by jkkj0414

## Description

> SQL문을 어떻게 구성했는지 설명해주세요.
- 테이블 1. 학생(student) - 학번num(PK), 학과department, 이름name
- 테이블 2. 과목(major) - 과목코드code(PK), 과목명subject, 학점credit, 교수명professor, 강의실class
- 테이블 3. 수강(course) - id(PK), 학번num(FK), 과목코드code(FK)

## Reference

> 참고한 레퍼런스가 있다면 기록해주세요.

2022-11-11 10:50 UTC, vact19 approved these changes
룩스굿뚜미

2022-11-11 14:03 UTC, vact19 requested changes
4. 수강 테이블에서 학생, 과목 테이블을 JOIN 연산하고 데이터를 보여준다 -> 수강 테이블에서 학생, 과목 테이블 함께 조인해야 합니다!

2022-11-13 06:34 UTC, vact19 approved these changes
좋아여

2022-11-14 00:31 UTC, HanHyunsoo approved these changes

2022-11-14 00:32 UTC, HanHyunsoo commented
[https://www.jetbrains.com/help/idea/creating-diagrams.html](https://www.jetbrains.com/help/idea/creating-diagrams.html)

참고하세요! 다이어그램을 png 형태로 내보낼 수 있어요!

고생하셨습니당.

2022-11-14 03:01 UTC, merged